window.ABIGAIL_PROJECTS = [
  {
    id: "uncommon-grace",
    title: "(UN)CASUAL WARDROBE JULY 2026",
    category: "editorial",
    categoryLabel: "Editorial",
    year: "2026",
    client: "Roll Up Magazine",
    description: "",
    concept: "",
    credits: {
  "Styling & AD": "Abigail Diantete @dia.monna",
  "Photographer": "Matthieu Gorin @matthieugorin_",
  "MUA & Hairstylist": "Asma Nafati @asmanafatimua",
  "Models": "Nils Foulon @nils.foulon from @nextparis & Mila Chistiakova @52x25 from @marilynagencyparis"},
    images: ["assets/images/editorial/roll-up-mag/uncommon-grace-01.jpg", "assets/images/editorial/roll-up-mag/uncommon-grace-02.jpg", "assets/images/editorial/roll-up-mag/uncommon-grace-03.jpg" ,  "assets/images/editorial/roll-up-mag/4.jpg",  "assets/images/editorial/roll-up-mag/5.jpg", "assets/images/editorial/roll-up-mag/6.jpg", "assets/images/editorial/roll-up-mag/7.jpg", "assets/images/editorial/roll-up-mag/8.jpg"]
  },
  {
    id: "second-skin",
    title: "EPICURE",
    category: "editorial",
    categoryLabel: "Editorial",
    year: "2025",
    client: "FGUK Magazine Online",
    description: "",
    concept: "",
    credits: {
  "Photographer": "Aubane Després",
  "Styling": "Martina Bruna",
  "Pastry Chef": "Florian Mongaï",
  "Video DOP / Edit / Color": "Anthony Peyper",
  "Set Designer": "Agathe Reille Soult",
  "Stylist Assistants": "Emma Moulay & Abigail Diantete",
  "Photographer Assistant": "Marine Brilloit",
  "Video Assistant": "Vicktor Podcacha",
  "Model": "Sarang Cheoung / Urban Models Management",
  "Make-Up Artist": "Mathilde Gasparini",
  "Hair Stylist": "Stef Worldhair"},
    images: ["assets/images/editorial/epicure/second-skin-01.jpg", "assets/images/editorial/epicure/second-skin-02.jpg", "assets/images/editorial/epicure/second-skin-03.jpg", "assets/images/editorial/epicure/4.jpg", "assets/images/editorial/epicure/5.jpg", "assets/images/editorial/epicure/6.jpg", "assets/images/editorial/epicure/7.jpg", "assets/images/editorial/epicure/8.jpg"],
    videos : [ "assets/videos/epicure-video.mov"]
  },
  {
    id: "after-hours",
    title: "WARDROBE WARS",
    category: "editorial",
    categoryLabel: "Editorial",
    year: "2025",
    client: "Schema Magazine",
    description: "",
    concept: "",
    credits: {
  "Photographer": "Lebon Bourgeois @lebonbourgeois",
  "EIC": "Sara Bastai @sarabastai",
  "Artistic Direction": "Sylvia Perez @sylvia_perezperez",
  "Stylist": "Julianne Courtois @juliannecourtois",
  "Make-Up Artist": "Kamila Vay @kamilavay",
  "Hair Stylist": "Rimi Ura @rimiura",
  "Set Designer": "Milena Krastev @milenakrastev",
  "Nail Artist": "Delphine Aissi @delphineaissi",
  "Light Assistant": "Baptiste Zysman @baptiste_zysman",
  "Stylist Assistant": "Abigail Diantete",
  "Special Thanks": "Thomas Manil @thomas_manil"},
    images: ["assets/images/editorial/shema-magazine/after-hours-01.jpg", "assets/images/editorial/shema-magazine/after-hours-02.jpg", "assets/images/editorial/shema-magazine/after-hours-03.jpg" , "assets/images/editorial/shema-magazine/after-hours-04.jpg" , "assets/images/editorial/shema-magazine/after-hours-05.jpg" , "assets/images/editorial/shema-magazine/after-hours-06.jpg"]
  },
  {
    id: "soft-armour",
    title: "F*CKING YOUNG! ONLINE",
    category: "editorial",
    categoryLabel: "Editorial",
    year: "2026",
    client: "Fucking Young!",
    description: "",
    concept: "",
    credits: {
  "Talent": "Giovani Zattera",
  "Photographer": "Rebecca Dorothy",
  "Stylist": "Martina Bruna",
  "Stylist Assistant": "Abigail Diantete",
  "MUA": "Takako",
  "Photography Assistants": "Thomas Makhlouf & Mathilde Bono",
  "Interview": "Anna Rose Barr" },
    images: ["assets/images/editorial/giovanni-x-fy/soft-armour-01.jpg", "assets/images/editorial/giovanni-x-fy/soft-armour-02.jpg", "assets/images/editorial/giovanni-x-fy/soft-armour-03.jpg", "assets/images/editorial/giovanni-x-fy/4.jpg", "assets/images/editorial/giovanni-x-fy/5.jpg", "assets/images/editorial/giovanni-x-fy/6.jpg", "assets/images/editorial/giovanni-x-fy/7.jpg", "assets/images/editorial/giovanni-x-fy/8.jpg", "assets/images/editorial/giovanni-x-fy/9.jpg", "assets/images/editorial/giovanni-x-fy/10.jpg"]
  },
  {
    id: "in-transit",
    title: "CRASH",
    category: "editorial",
    categoryLabel: "Editorial",
    year: "2026",
    client: "S&M Magazine Issue 3",
    description: "",
    concept: "",
    credits: {
  "Photographer": "Rebecca Dorothy",
  "Stylist": "Martina Bruna",
  "Stylist Assistant": "Abigail Diantete",
  "Make-Up": "Roscino Makeup",
  "Hair": "Romain Duplessy",
  "Casting": "Elisa Villa & Millemila Baci",
  "Models": "Juliaryan Murray & Valya Fedotova — Supreme Management" },
    images: ["assets/images/editorial/crash-s&m/in-transit-01.jpg", "assets/images/editorial/crash-s&m/in-transit-02.jpg", "assets/images/editorial/crash-s&m/in-transit-03.jpg" ,  "assets/images/editorial/crash-s&m/3.jpg",  "assets/images/editorial/crash-s&m/4.jpg" , "assets/images/editorial/crash-s&m/5.jpg" , "assets/images/editorial/crash-s&m/6.jpg" , "assets/images/editorial/crash-s&m/7.jpg" , "assets/images/editorial/crash-s&m/8.jpg" , "assets/images/editorial/crash-s&m/9.jpg" , "assets/images/editorial/crash-s&m/10.jpg" , "assets/images/editorial/crash-s&m/11.jpg"]
  },
  {
    id: "common-ground",
    title: "24S X COPERNI",
    category: "campaign",
    categoryLabel: "Campaign",
    year: "2023",
    client: "24S",
    description: "",
    concept: "",
    credits: {
  "Styling": "Manon Del Colle",
  "Styling Assistant": "Abigail Diantete",
  "Photography": "Studio L’Etiquette",
  "Art Direction": "Aubéry Lambert",
  "Set Design": "Julien Cavallina",
  "Hair & Makeup": "Aurore Gibrien" },
    images: ["assets/images/campaign/24SxCoperni/common-ground-01.jpg", "assets/images/campaign/24SxCoperni/common-ground-02.jpg", "assets/images/campaign/24SxCoperni/common-ground-03.jpg", "assets/images/campaign/24SxCoperni/4.jpg", "assets/images/campaign/24SxCoperni/5.jpg", "assets/images/campaign/24SxCoperni/6.jpg"]
  },
  {
    id: "parisian-playground",
    title: "PARISIAN PLAYGROUND",
    category: "campaign",
    categoryLabel: "Campaign",
    year: "2024",
    client: "LVMH PRIZE x 24S",
    description: "",
    concept: "",
    credits: {
  "Brands": "Better — Setchu — Magliano",
  "Styling": "Manon Del Colle",
  "Styling Assistant": "Abigail Diantete",
  "Photography": "Gabriel Boyer",
  "Film Director": "Gabriel Mokayed",
  "Art Direction": "Aubéry Lambert",
  "Hair": "Charlotte Dubreuil Gourion",
  "MUA": "Loren Boss",
  "Production": "Kartel Paris"},
    images: ["assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/1.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/2.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/3.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/4.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/5.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/6.jpg"]
  },
  {
    id: "summer-2024",
    title: "SUMMER 2024",
    category: "campaign",
    categoryLabel: "Campaign",
    year: "2026",
    client: "24S",
    description: "",
    concept: "",
    credits: { Styling: "Abigail Diantete" },
    images: ["assets/images/campaign/SUMMER-2024/1.jpg", "assets/images/campaign/SUMMER-2024/2.jpg", "assets/images/campaign/SUMMER-2024/3.jpg", "assets/images/campaign/SUMMER-2024/4.jpg" , "assets/images/campaign/SUMMER-2024/5.jpg", "assets/images/campaign/SUMMER-2024/6.jpg"],
    videos: ["assets/videos/24S_summer_légé.mov","assets/videos/24S_x_ERES_légé.mov" ]
  },
  {
    id: "objects-in-motion",
    title: "BOTH PARIS",
    category: "campaign",
    categoryLabel: "Campaign",
    year: "2025",
    client: "BOTH PARIS",
    description: "",
    concept: "",
    credits: { 
  "Photographer": "Elliott SB",
  "Stylist": "Abigail Diantete",
  "HMU": "Leah Bedfert",
  "Model": "Emma Galwas",
  "Production Coordinator": "Camille Badée" },
    images: ["assets/images/campaign/BOTH/objects-in-motion-01.jpg", "assets/images/campaign/BOTH/objects-in-motion-02.jpg", "assets/images/campaign/BOTH/objects-in-motion-03.jpg", "assets/images/campaign/BOTH/4.jpg", "assets/images/campaign/BOTH/5.jpg", "assets/images/campaign/BOTH/6.jpg", "assets/images/campaign/BOTH/7.jpg"]
  },
  {
    id: "maya-k",
    title: "LES FLAMMES",
    category: "talents",
    categoryLabel: "Talents",
    year: "2026",
    client: "Artist Portrait",
    description: "",
    concept: "",
    credits: { Photography: "Théo Benali", Styling: "Abigail Diantete", Talent: "Maya K.", Makeup: "Eva Nsimba", Management: "Parallel Artists" },
    images: ["assets/images/talents/maya-k-01.jpg", "assets/images/talents/maya-k-02.jpg", "assets/images/talents/maya-k-03.jpg", "assets/images/talents/4.jpg", "assets/images/talents/5.jpg"]
  },
  
  {
    id: "family-archive",
    title: "SHOOT ATMANE",
    category: "personal",
    categoryLabel: "Personal Projects",
    year: "2026",
    client: "Personal Project",
    description: "",
    concept: "",
    credits: {
  "Photographer": "Prosper Panhard",
  "Stylist": "Abigail Diantete",
  "Model": "Atmane Yousfi — Next Paris"},
    images: ["assets/images/personal/26_03 Propser Panhard/9.jpg", "assets/images/personal/26_03 Propser Panhard/family-archive-01.jpg", "assets/images/personal/26_03 Propser Panhard/family-archive-02.jpg", "assets/images/personal/26_03 Propser Panhard/family-archive-03.jpg", "assets/images/personal/26_03 Propser Panhard/4.jpg", "assets/images/personal/26_03 Propser Panhard/5.jpg", "assets/images/personal/26_03 Propser Panhard/6.jpg", "assets/images/personal/26_03 Propser Panhard/7.jpg", "assets/images/personal/26_03 Propser Panhard/8.jpg"]
  },
  {
    id: "blue-room",
    title: "SHOOT LUIGI",
    category: "personal",
    categoryLabel: "Personal Projects",
    year: "2025",
    client: "Personal Project",
    description: "",
    concept: "",
    credits: { 
  "Photographer": "Luigi Cianfarano",
  "Stylist": "Martina Bruna",
  "Stylist Assistant": "Abigail Diantete",
  "HMU": "Raphaële Parot",
  "Model": "Eduarda Bretas — IMG Paris"},
    images: ["assets/images/personal/SHOOT-LUIGI/blue-room-01.jpg", "assets/images/personal/SHOOT-LUIGI/blue-room-02.jpg", "assets/images/personal/SHOOT-LUIGI/blue-room-03.jpg", "assets/images/personal/SHOOT-LUIGI/4.jpg", "assets/images/personal/SHOOT-LUIGI/5.jpg", "assets/images/personal/SHOOT-LUIGI/6.jpg", "assets/images/personal/SHOOT-LUIGI/7.jpg", "assets/images/personal/SHOOT-LUIGI/8.jpg"]
  },
  {
    id: "sunday-uniform",
    title: "SHOOT RIA",
    category: "personal",
    categoryLabel: "Personal Projects",
    year: "2024",
    client: "Personal Project",
    description: "",
    concept: "",
    credits: {
  "Photographer": "Ria Mort",
  "Stylist": "Abigail Diantete",
  "Makeup": "Thomas Kergot",
  "Model": "Rui Wang — Next Paris"
},
    images: ["assets/images/personal/SHOOT-RIA/sunday-uniform-01.jpg", "assets/images/personal/SHOOT-RIA/sunday-uniform-02.jpg", "assets/images/personal/SHOOT-RIA/sunday-uniform-03.jpg", "assets/images/personal/SHOOT-RIA/4.jpg", "assets/images/personal/SHOOT-RIA/5.jpg", "assets/images/personal/SHOOT-RIA/6.jpg"]
  }
];
